#!/bin/bash
# Wrapper script for make-golang-vendor.bashlib

if [[ ${BASH_SOURCE} = */* ]]; then
	SCRIPT_DIR=${BASH_SOURCE%/*}/
else
	SCRIPT_DIR=./
fi

. ${SCRIPT_DIR}/make-golang-vendor.bashlib || { echo "Failed to source make-golang-vendor.bashlib!" ; exit 1 ; }

# Extract version from input args
vendor_common_extract_version "$1" "app-builder" "APP_BUILDER_VERSION"

# Set SOURCE_DATE_EPOCH based on GitHub tag date
if [[ -n "$APP_BUILDER_VERSION" ]]; then
	get_github_tag_date "develar/app-builder" "v${APP_BUILDER_VERSION}"
fi

export APP_BUILDER_VENDOR_TARBALL=0
export ABI_X86="64" # we don't want to build multiple variants & easier to glob below

# Filter out the --deps/--vendor options from the arguments since we're explicitly setting the mode
filtered_args=()
for arg in "$@"; do
	case "$arg" in
		--deps|--vendor|--mode=*)
			# Skip these options as we're setting the mode explicitly
			veinfo "Skipping argument: $arg"
			;;
		*)
			filtered_args+=("$arg")
			;;
	esac
done

vendor-golang --vendor "${filtered_args[@]}"
