#!/usr/bin/python2
# Copyright 2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

"""Extracts V8 version number based on given version.cc file."""

import sys

import chromium_tools

print chromium_tools.v8_extract_version(open(sys.argv[1]).read())
